### ISSUE TITLE
4-op mode bug 

### ISSUE THREAD

**Issue by freq-mod** [nukeykt/Nuked-OPL3#18]
After toggling 4-op mode, the slots are disconnected which causes the channel to be muted.

More info: 
![image](https://user-images.githubusercontent.com/32672779/184553160-8e9a4ce6-5957-4f28-8213-addfef124386.png)

**Comment by Kagamiin** [comment]
This was fixed by: https://github.com/nukeykt/Nuked-OPL3/pull/21

@nukeykt I believe you can close this.
